### ISSUE TITLE
Какие планы?

### ISSUE THREAD

**Issue by kotoshii** [gnoemes/Shimori#2]
Привет, хочу узнать, планируешь ли ты после завершения работы над Shimori допиливать онлайн просмотр для него? Или какие у тебя вообще на это планы?

**Comment by gnoemes** [comment]
> Привет, хочу узнать, планируешь ли ты после завершения работы над Shimori допиливать онлайн просмотр для него? Или какие у тебя вообще на это планы?


Привет.
Хочу сделать из шимори платформу, где можно будет удобно смотреть и читать. Сперва запилю основной функционал приложения, потом перейду к части с просмотром/чтением.

**Comment by kotoshii** [comment]
> Привет. Хочу сделать из шимори платформу, где можно будет удобно смотреть и читать. Сперва запилю основной функционал приложения, потом перейду к части с просмотром/чтением.

Понял тебя. И как продвигается разработка в плане основных функциональностей? Стоит ли ждать каких либо релизов в ближайшие несколько месяцев?

**Comment by gnoemes** [comment]
> И как продвигается разработка в плане основных функциональностей

База готова на 40%. Сами экраны не долго добавить.

> Стоит ли ждать каких либо релизов в ближайшие несколько месяцев?

Пока нет времени заниматься проектом на постоянной основе. А так, планирую выпустить бетку в начале осени.

**Comment by kotoshii** [comment]
> Пока нет времени заниматься проектом на постоянной основе. А так, планирую выпустить бетку в начале осени.

Понял, спасибо за ответ. Буду ждать.
